# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Minima"
license = "MIT"
licenselink = "https://github.com/mivinci/minima/blob/master/LICENSE"
description = "A clean and minimal Hugo theme"
homepage = "https://github.com/mivinci/hugo-theme-minima"
tags = [
    "minimal", 
    "clean", 
    "blog", 
    "responsive", 
    "personal", 
    "simple", 
    "minimalist", 
    "portfolio", 
    "dark",
]
features = [
    "Dark mode", 
    "Multilingual mode", 
    "KaTeX", 
    "Mermaid",
    "Code highlighting", 
    "External link",
    "RSS",
]
min_version = "0.85.0"

[author]
name = "Mivinci"
homepage = "https://mivinci.github.io/hugo-theme-minima"

# If porting an existing theme
[original]
name = "Minima"
homepage = "https://adisaktijrs.github.io/minima"
repo = "https://github.com/adisaktijrs/hexo-theme-minima"
