baseURL: https://mivinci.github.io/hugo-theme-minima
languageCode: en-us
title: Hugo on Minima
copyright: © 2020-2023 X
googleAnalytics:
# paginate specifies the maximum number of posts displayed on the home page.
paginate: 12
# theme specifies the name of the theme to be used.
theme: hugo-theme-minima
# defaultContentLanguage specifies the default language to use.
defaultContentLanguage: en
# language.xxx setup
languages:
  en:
    languageName: EN # will be displayed in the navbar.
    weight: 1
  zh-cn:
    languageName: 简中 # will be displayed in the navbar.
    weight: 2
    author:
      status: 目前住在地球 🌍
      description: |
        这是 Minima, 一个简洁的 Hugo 主题，移植自 [Hexo Minima](https://github.com/adisaktijrs/hexo-theme-minima)。
        支持深色模式、多语言、数学公式、流程图、代码语法高亮，当然还有分类、标签、系列等等。
    params:
      greet: 你好 :)

# author specifies your name, a slogon and your brief self-introduction.
author:
  name: X
  status: Currently living on Earth 🌍
  description: |
    This is Minima, a clean and minimal Hugo theme porting from 
    [Hexo Minima](https://github.com/adisaktijrs/hexo-theme-minima). It has supports 
    for dark mode, multilingual mode, math formulas, flowcharts, syntax highlighting, 
    and of course taxonomies like categories, tags, and series.

params:
  # greet specifies greeting words.
  greet: Hello :)
  # subtitle speficies a subtitle displayed right after the site title.
  subtitle:
  # switch specifies two emojis used as the button toggling color themes.
  switch: ["🌚", "🌝"]
  # minima has one dark theme and multiple light themes. defaultTheme specifies
  # a default light theme to use. currently available options: light, sand, rock, system.
  defaultTheme: light
  # displayDate speficies whether or not to display post date on the home page.
  displayDate: true
  # displayDescription specifies whether or not to display post description on
  # the hoem page.
  displayDescription: true
  # selectable specifies if or not your post content can be selected.
  selectable: true
  # social is an array containing as many as social accounts to be displayed
  # in the buttom of every page.
  social:
    - name: "twitter"
      url: "https://twitter.com/realmivinci"
    - name: "email"
      url: "mailto:mivinci@qq.com"
    - name: "github"
      url: "https://github.com/mivinci/hugo-theme-minima"
    - name: "rss"
      url: "/index.xml"

  # math plugin
  math:
    enable: false
    provider: katex

  # diagram plugin
  diagram:
    enable: false
    provider: mermaid

  # comment plugin
  comment:
    enable: true
    provider: giscus
    # check out https://disqus.com/
    disqus:
      shortname: hugo-minima
      # check out https://utteranc.es
    utterances:
      repo: mivinci/hugo-theme-minima
      issueTerm: pathname
      label: comment
    # check out https://giscus.app
    giscus: 
      repo: mivinci/hugo-theme-minima
      repoId: MDEwOlJlcG9zaXRvcnkzODcxMjM2NDU=
      category: Comments
      categoryId: DIC_kwDOFxMJvc4CScQm
      mapping: pathname
      inputPosition: buttom # bottom | top
      reactions: true
      metadata: false

  # search plugin
  search:
    enable: true
    provider: fuse
    title: Search
    placeholder: Enter keywords
    # check out https://fusejs.io
    fuse:
      keys:
        - title
        - permalink
        - summary
        - content
      distance: 100
      location: 0
      threshold: 0.6
      ignoreLocation: false
      isCaseSensitive: false
      includeScore: false
      includeMatches: false
      minMatchCharLength: 1
      shouldSort: true
      findAllMatches: false


# menu.main is an array containing what is used as the navigator.
menu:
  main:
    - identifier: tags
      name: Tags
      weight: 1
    - identifier: series
      name: Series
      weight: 2
    - identifier: search
      name: 🔍
      weight: 3

# taxonomies defines ways to classify yout posts. Below are some presets that
# most bloggers use, so you can replace them with whatever you like.
taxonomies:
  category: categories
  tag: tags
  series: series

# outputs tells Hugo the kind of files to be rendered.
outputs:
  home:
    - HTML
    - RSS
    - JSON

# markup.highlight has two keys set to make sure that the syntax highlighting
# in your posts are rendered correctly, so DO NOT edit them.
markup:
  highlight:
    lineNos: true
    noClasses: false
